FROM node:22-alpine AS builder

WORKDIR /home/node/app

COPY package.json package-lock.json ./
RUN npm ci

COPY src ./src
COPY dotenv.d.ts tsconfig.json ./
RUN npx tsc && \
    npm prune --production

FROM node:22-alpine

WORKDIR /home/node/app

RUN mkdir -p /home/node/app/assets && \
    chown node:node /home/node/app/assets && \
    mkdir -p /home/node/app/dist/assets && \
    chown node:node /home/node/app/dist/assets

COPY --from=builder --chown=node:node /home/node/app/package.json .
COPY --from=builder --chown=node:node /home/node/app/package-lock.json .
COPY --from=builder --chown=node:node /home/node/app/node_modules ./node_modules
COPY --from=builder --chown=node:node /home/node/app/dist ./dist

USER node
ENV NODE_ENV=production
EXPOSE 9095

HEALTHCHECK --interval=30s --timeout=3s \
  CMD node -e "require('http').get('http://localhost:9095/health', (r) => {if(r.statusCode !== 200) throw new Error()})"

CMD ["node", "dist/src/index.js"]
