version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .github/Dockerfile
      args:
        NODE_ENV: development
        BUILD_TIMESTAMP: ${BUILD_TIMESTAMP}
        BRANCH: ${BRANCH:-main}
    volumes:
      - ../:/workspace
      - ../assets:/home/node/app/dist/assets
    ports:
      - "9095:9095"
    environment:
      - NODE_ENV=development
      - PORT=9095
      - PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY:-}
      - PUSHOVER_API_TOKEN=${PUSHOVER_API_TOKEN:-}
    working_dir: /workspace
    user: node
    stdin_open: true
    tty: true
